name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Checkout the Latest Package Code
        uses: actions/checkout@v3
      - name: Setup Pulsar Editor
        uses: pulsar-edit/action-pulsar-dependency@v3.3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install deps
        run: npm install
      - name: Run the headless Pulsar Tests
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: pulsar --test spec
